const demandaId = Number(new URLSearchParams(window.location.search).get("id"));
const documento = document.getElementById("relatorio-documento");
const li = (itens) => itens && itens.length ? `<ul>${itens.map((x) => `<li>${escaparHtml(x)}</li>`).join("")}</ul>` : "<p>Não informado.</p>";

async function carregar() {
    try {
        const r = await apiInstitucionalFetch(`/institucional/demandas/${demandaId}/relatorio-formal`);
        const rastreabilidade = r.rastreabilidade || {};
        documento.innerHTML = `<div class="relatorio-cabecalho"><p class="pequeno">AMAZONAS COMUNIDADES</p><h1>${escaparHtml(r.cabecalho)}</h1><p><strong>Protocolo:</strong> ${escaparHtml(r.protocolo)}</p></div><hr><h2>${escaparHtml(r.titulo)}</h2><p><strong>Comunidade:</strong> ${escaparHtml(r.comunidade)}</p><p><strong>Categoria:</strong> ${escaparHtml(r.categoria)}${r.subcategoria ? ` / ${escaparHtml(r.subcategoria)}` : ""}</p><p><strong>Período analisado:</strong> ${formatarData(r.periodo.inicio)} a ${formatarData(r.periodo.fim)}</p><p><strong>Relatos relacionados:</strong> ${r.quantidade_relatos}</p><p><strong>Prioridade:</strong> ${escaparHtml(rotuloPrioridade(r.prioridade))} • <strong>Janela:</strong> ${escaparHtml(r.janela_encaminhamento)}</p><h3>Síntese da demanda</h3><p>${escaparHtml(r.sintese)}</p><h3>Necessidades identificadas nos relatos</h3>${li(r.necessidades)}<h3>Recursos mencionados</h3>${li(r.recursos_disponiveis)}<h3>Divergências preservadas</h3>${li(r.divergencias)}<h3>Informações ainda faltantes</h3>${li(r.informacoes_faltantes)}<h3>Manifestação comunitária</h3>${r.manifestacoes_comunitarias.length ? r.manifestacoes_comunitarias.map((m) => `<p><strong>${escaparHtml(m.tipo)} — ${escaparHtml(m.autor)}:</strong> ${escaparHtml(m.texto)}</p>`).join("") : "<p>Aguardando manifestação.</p>"}<h3>Rastreabilidade</h3><p>Relatos originais preservados: sim. Comunidade catalogada: ${rastreabilidade.comunidade_catalogada ? "sim" : "não"}. Localização comunitária catalogada: ${rastreabilidade.localizacao_comunitaria_catalogada ? "sim" : "não"}.${rastreabilidade.fonte_localizacao ? ` Fonte territorial: ${escaparHtml(rastreabilidade.fonte_localizacao)}.` : ""} Origens registradas: ${escaparHtml(JSON.stringify(rastreabilidade.origens || {}))}.</p><h3>Encaminhamentos</h3>${r.encaminhamentos.length ? r.encaminhamentos.map((e) => `<p>${e.ordem}. <strong>${escaparHtml(e.instituicao)}</strong> — ${escaparHtml(e.status)}${e.demonstracao ? " (instituição de demonstração)" : ""}</p>`).join("") : "<p>Ainda não encaminhada.</p>"}<div class="nota-relatorio"><strong>Nota metodológica:</strong> ${escaparHtml(r.nota_metodologica)}</div>`;
    } catch (erro) { documento.textContent = erro.message; }
}
carregar();
